### ISSUE TITLE
Cannot Find Source code/file (.yml) for configuring service page, about page or project page

### ISSUE THREAD

**Issue by austinwilhelm6** [themefisher/airspace-hugo#100]
I am currently using GitLab to create a website, however as I have been going through the directories -- I can customize everything else, but I want to use these three page types as a template but cannot find the files to change the "/sitename". 

Let me know if there are any easy solutions or what I should do!

**Comment by developer-evan** [comment]
Hey @austinwilhelm6 
I didn't understand what you are saying, can you please explain a little bit more so i can understand. However, you can find those file in `examleSite/data/` folder. thanks

**Comment by austinwilhelm6** [comment]
@developer-evan Hey Evan! so there are (2) issues I am having, both sort of related to each other
**(1)** within the examplesite/data/ folder on my repo, there is only about.yml, homepage.yml, pricing.yml and service.yml - I need to configure the **project** template page.

**(2)** Right now, I have set up and configured the service.yml, but cannot change its sub-directory name on my website to something else. I just want the naming convention of the directory to match the title I have on the main menu. 

Example: mysite.com/**service** -> mysite.com/**why-us**

**Comment by developer-evan** [comment]
hey @austinwilhelm6 

1. All project item comes from `content/pojects` folder. Project page has only the project item. If you want to change the page structure, then you need to edit the project page layout.

2. When you want to change the page directory, you also need to change the folder name in `content` folder, and also change the name from `layout` folder (if it has a layout). you can find more about it on https://docs.gethugothemes.com/guide

**Comment by developer-evan** [comment]
Hello @austinwilhelm6 ,

I am going to close this issue, if you have any more queries, then don't hesitate to re-open it.
