### ISSUE TITLE
Inserting Images!

### ISSUE THREAD

**Issue by austinwilhelm6** [themefisher/airspace-hugo#102]
Hey there -- so i've been using the traditional gitlab/markdown language to insert images.. I can see them in preview on gitlab, however they do not populate on the site I'm building!

Ex: "< img src="static/images/support/gs-1.png" width="500" /> </br>"

If there is another way I can get the images or even gifs to populate, that would be awesome to know!

**Comment by developer-evan** [comment]
Hello @austinwilhelm6 ,

I want to know where you put this image? Without knowing this, I can't help you. It will be great if you also share a screenshot with us. thank you

**Comment by austinwilhelm6** [comment]
Yeah, so I tried to insert it on one of the blog layout pages just in a simple content area. The first image is the gitlab markdown editor and the second image is the rendered site. 

<img width="1181" alt="Screen Shot 2020-10-15 at 9 07 05 AM" src="https://user-images.githubusercontent.com/71775128/96140888-1004de00-0ec6-11eb-9db2-e0cb32cc62c5.png">
<img width="781" alt="Screen Shot 2020-10-15 at 9 07 24 AM" src="https://user-images.githubusercontent.com/71775128/96140903-13986500-0ec6-11eb-97bd-5e701edca461.png">

**Comment by developer-evan** [comment]
Hi @austinwilhelm6

It should work. However, it's not working for you. can you try to insert this image in markdown format? (i.e. `![image name](../image-path/image.png)`). Or you can share your live URL so I can investigate what's going wrong here. Thank you

**Comment by austinwilhelm6** [comment]
so I used the markdown format you recommended at this [address in particular ](http://catsone.com-2020.s3-website-us-east-1.amazonaws.com/support/candidates/sending-sms/) 

The image shows up, but there is no way I've found online that I can format it and it also oversteps the boundaries on the side. 

Is there an easy way to just get single-pages without the side widget?

**Comment by austinwilhelm6** [comment]
Also, if you use the link from above -- I want to be able to create a separate category system so the blog and support articles can be organized separately -- if I could get some guidance on this, that would be awesome!

**Comment by developer-evan** [comment]
Hi @austinwilhelm6 

I have fixed the image responsive issue, And you can handle categories by following this doc https://gohugo.io/content-management/taxonomies/

thanks

**Comment by developer-evan** [comment]
Hello @austinwilhelm6

Did it fix your issue? I am going to close this issue, If you fetch any issue, you can re-open it. 

Also if you like this theme, a star to the repository would be fantastic.
