### ISSUE TITLE
add the support to Open Graph

### ISSUE THREAD

**Issue by augustincl** [themefisher/airspace-hugo#107]
First, thanks for your contribution and sharing on the github ❤️ 

I have one suggestion for you. Because the social media, like FB, uses Open Graph as their cache policy, however, I don't see those meta are added into HEAD, so I would like to recommend to add that into the implementation.

Actually, I have prepare a patch for that, but it seems I can't create any PR. I just attach the patch here for your reference 😄 

[0001-feat-partials-add-supports-to-Open-Graph.txt](https://github.com/themefisher/airspace-hugo/files/5715021/0001-feat-partials-add-supports-to-Open-Graph.txt)

**Comment by somratpro** [comment]
Hello @augustincl 

thank you for your suggestion, we will add this in our next update.
