### ISSUE TITLE
Update errors

### ISSUE THREAD

**Issue by jpflores-13** [themefisher/airspace-hugo#111]
Hello, I was wondering if I can get some assistance on this error. I'm trying to deploy my site via Netlify.

ERROR 2021/01/06 19:28:22 AIRSPACE-HUGO theme does not support Hugo version 0.54.0. Minimum version required is 0.64.0
Building sites … Total in 157 ms
Error: Error building site: logged 1 error(s)

**Comment by somratpro** [comment]
Hello @jpflores-13 

You need to update your netlify settings, go to `netlify.toml` and update the hugo version. or you can use our provided netlify settings with the theme. to do it, please follow this doc https://docs.gethugothemes.com/guide. thank you

**Comment by somratpro** [comment]
I am going to close this issue, if you face any more problem then create a new issue.
