### ISSUE TITLE
Obsolete SCSS files?

### ISSUE THREAD

**Issue by salim-b** [themefisher/airspace-hugo#127]
While working on improving this theme, I noticed that there are two SCSS files under `assets/scss/` which do not appear to be used anywhere: **`home.scss`** and **`landing-page.scss`**

These files are neither [Sass partials](https://sass-lang.com/guide#topic-4) nor sourced by [Hugo templating (`resources.Get "..."`)](https://gohugo.io/hugo-pipes/scss-sass/) so **I wonder if I a PR removing these files is welcome**. Having these files in the theme is just unnecessarily confusing I think.

**Comment by somratpro** [comment]
Thanks for your concern, we will remove it in our next update.

**Comment by salim-b** [comment]
Here you go: https://github.com/themefisher/airspace-hugo/pull/129 :slightly_smiling_face:
