### ISSUE TITLE
header navigation menu rel links issues with github pages

### ISSUE THREAD

**Issue by vce-open** [themefisher/airspace-hugo#157]
we plan to buy a domain so i am not sure if i have configured my `config.toml` wrong or is it real issue

used github actions and github pages to deploy and host website on `https://<org11>.github.io/<reponame>/` in top navigation menu pages are redirected to `/<reponame>/<reponame>/page` when the correct behaviour should be `/<reponame>/page`.

**Comment by vce-open** [comment]
hi i tried different versions to crosscheck, correct me if i am wrong is this proper `https://<org11>.github.io/<reponame>/` for base url

**Comment by salim-b** [comment]
> is this proper `https://<org11>.github.io/<reponame>/` for base url.

nope.

without `reponame`, just `https://<org11>.github.io` would be correct.

**Comment by vce-open** [comment]
that would be good if `<reponame>` is same as `<org_name> or <github-username>`  as per github pages offical docs, i have multiple hugo repos. 

And also if we have that as base url footer menu gives issues and pages get loading issues as images will load properly. I did verify that for just in case before raising request.

**Comment by vce-open** [comment]
i did try "Have you actually tried setting baseURL = "https://<org11>.github.io"?" will attach a video or gif of that behavior in a day or two.

is this a recent change on Hugo side "Hugo will prepend /<reponame>/" i am doing this for the college. All my personal hugo repos have custom domains and I either did not get this error or forgot if this happened to them, as i had the domain before hand.

can you mean time see this [hugo issue on github](https://github.com/gohugoio/hugo/issues/799
).


Thanks salim

**Comment by salim-b** [comment]
> is this a recent change on Hugo side (...)

No, I guess this problem only occurs when using GitHub Pages **project** sites in combination with a theme that uses relative URLs (like Airspace does).

> can you mean time see this [hugo issue on github](https://github.com/gohugoio/hugo/issues/799).

The issue you mention [has been fixed](https://github.com/gohugoio/hugo/commit/1cbdd3e59df6c4513ea8e83aadc969272420ca52) long time ago.
