### ISSUE TITLE
Not building with i18n folder

### ISSUE THREAD

**Issue by phil-pappas** [themefisher/airspace-hugo#159]
Hi. 

I tried to install the theme using the instructions of this video: https://www.youtube.com/watch?v=jrkvirglgaQ
but when I run `hugo server` I get an error. When I remove the folder i18n is running okay but I cannot see the context of i18n's folder in the UI.

I am attaching the log error from the terminal:
![image](https://user-images.githubusercontent.com/57324955/118117371-d52b4000-b3eb-11eb-9432-c3fa511000ec.png)

**Comment by salim-b** [comment]
Please try it with the latest Hugo version 0.83.1.

**Comment by phil-pappas** [comment]
That was the issue, thank you very much!
