### ISSUE TITLE
Service columns should be the same height

### ISSUE THREAD

**Issue by AlexanderWillner** [themefisher/airspace-hugo#165]
Steps that will reproduce the problem?
1. Modify a service description.
2. Open the service page.

What is the expected result?
All columns should be the same height.

What happens instead?
As soon as the service descriptions have different length, the columns will be different.

Possible workaround:
We need to add some `height: 100%` somewhere in the `scss` files.

Any additional information:

<img width="1680" alt="Screenshot 2021-05-18 at 16 33 35" src="https://user-images.githubusercontent.com/307605/118670413-e2cf3400-b7f6-11eb-970e-fc39e196674e.png">

**Comment by salim-b** [comment]
Feel free to submit a PR :)
