### ISSUE TITLE
Images and animation do not work on mobile platforms

### ISSUE THREAD

**Issue by gkzsolt** [themefisher/airspace-hugo#17]
Hi,
My wife found this theme and we were impressed by its truly professionally designed look: congratulations! However, it does not seem to work under any mobile platform: on Android, in the second section ("We believe in great ideas") the text overlaps the background image, on iOS the text is on the right, but the image is not displayed at all; neither the right hand side image on "About Us" (we tried the demo link [https://themes.gohugo.io/theme/airspace-hugo/](https://themes.gohugo.io/theme/airspace-hugo/)). Does this animation work at all on mobile ?
Thanks.

**Comment by anthonyfok** [comment]
Hi @gkzsolt,

Themefisher's original theme has actually been updated in recent months (as of March 2018), and it looks even better!

This Hugo port was originally created by @karjudev a year ago (mid-2017), so does not contain the latest refinement and features.  I happen to be making a new website for a friend, and have started updating this Hugo port based on Themefisher's latest version, and will be making Pull Requests in the coming days or weeks.  (Neither @karjudev nor I work for Themefisher, but both of us must be attracted to Themefisher's beautiful themes.)

> on Android, in the second section ("We believe in great ideas") the text overlaps the background image, on iOS the text is on the right, but the image is not displayed at all; neither the right hand side image on "About Us" (we tried the demo link https://themes.gohugo.io/theme/airspace-hugo/).

Please take a look at http://demo.themefisher.com/demos/?theme=airspace, and see if the problems you noticed are resolved or not.  (I noticed the "text overlaps the background image" problem too in a narrow browser window, but don't have an iOS device handy to test the other ones.)

What I found is that this theme is indeed quite responsive, but may need a little bit more fine-tuning, i.e tweaking the CSS.  So, yes, please report your experience of the latest upstream demo at http://demo.themefisher.com/demos/?theme=airspace, and I am sure @mehedi-sharif and his team at Themefisher will appreciate the feedback and resolve these issues.

**Comment by gkzsolt** [comment]
Hi @anthonyfok, 
Thank you for your very kind words. I checked the template demo at themefisher.com, and unfortunately it had the same problems, so the port was good 😊. I'll try reporting this to them, although I feel a bit strange since I haven't paid for it. I am also doing this for somebody, and being a developer myself I'll try to dig a bit, just I am new to Hugo.

**Comment by gkzsolt** [comment]
I found the problem: it is the `background-attachment: fixed` property which is not honored on some devices and browsers. See this [StackOverflow](https://stackoverflow.com/questions/28532327/background-attachmentfixed-not-working-android-chrome-v40) report (for Chrome 40). This is the [bug report](https://issuetracker.google.com/issues/36908439) on Google Issue Tracker.
The issue has been here for a long time (was reported on 2009) and since then many workarounds have been advised, but the problem persists (Chrome becoming the new "IE problem" for web developers). Instead of going through all I choose to work around fiddling with background properties on different media queries. I did not reach the desired fixed background behaviour, but at least got a decent page flow on every device here.

Browsers/devices with the issue:
- Chrome 67.0 on Android 7.0 on a 6" tablet
- Chrome 67.0 on Android 6.0 on a phone
- Safari on iOS 9.3 on iPad mini  (this is one of the worst)

Your link to the demo does not have reporting links, and on themefischer.com you can only submit a ticket. I understand what you said about tweaking the CSS ;) Otherwise the theme is really astonishing, and makes a nice template, too bad for the cross-device issues.

**Comment by mehedi-sharif** [comment]
Hello @gkzsolt  ,
Sorry for late reply. I think those are silly issues. Did you fix them or not let me know. If you hopefully I will fix those in next update. Thanks for your feedback.
Thanks

**Comment by divinerites** [comment]
Thanks for this great work @mehedi-sharif 
I have those same problems and where about to look in.
But as you already have a hack/solution @gkzsolt , I'll wait and be more than happy to help debugging either hack or proper solution.

**Comment by gkzsolt** [comment]
My solution/workaround is below:
```
#feature {
  background: url("../img/great-ideas-bg.jpg");
  width: 100%;
  display: block;
  position: relative;
  overflow: visible;
  background-repeat: no-repeat;
  background-position: left center;
  background-color: #fff;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  padding: 100px 0;
}

/*------------------------------------
  iPad mini in landscape
-------------------------------------*/
@media only screen 
and (min-device-width : 768px) 
and (max-device-width : 1024px) 
and (orientation : landscape)
and (-webkit-min-device-pixel-ratio: 1)  {
  #feature {
    background: url("../img/great-ideas-bg-mini.jpg");
    /* background-attachment: fixed; DOES NOT WORK */
  }
}

/*--------------------------------------------
  Desktop, Chromebook: sliding over background
---------------------------------------------*/
@media (min-width: 992px) {
  #feature {
    background-attachment: fixed;
  }
}

/*------------------------------------
  Tablets and phones: flat background
-------------------------------------*/
@media only screen 
and (max-width: 991px) {
  #feature {
    background: #D0C3B8;
  }
}
```
You will notice that I renamed the background image and I made a new one for iPad mini. I had to play with its dimensions, however, for the image to be displayed correctly. It is not fixed, however (scrolls with the text there). I did not test it on a "normal" iPad.
If you have better ideas, don't hesitate to tell.

**Comment by divinerites** [comment]
@gkzsolt that's accurate. I used your hack.
And added the image in the contact section (so mobiles will see this photo).
That makes it for me. thanks.
