### ISSUE TITLE
FAQ Page Design

### ISSUE THREAD

**Issue by vegetarianinvestor** [themefisher/airspace-hugo#172]
The current FAQ page design isn't in a question and answer format like the [standard ones](https://in.pinterest.com/dotcomglobal/faq-pages-website-design/). Can the hugo theme be tweaked or configured to have a different format in which FAQ's could be categorized and listed in a question & answer format that could be possibly expanded and collapsed?

Thanks.

**Comment by salim-b** [comment]
> The current FAQ page design isn't in a question and answer format like the [standard ones](https://in.pinterest.com/dotcomglobal/faq-pages-website-design/).

Currently, the [FAQ content](https://github.com/themefisher/airspace-hugo/blob/master/exampleSite/content/english/faq.md) is written as plain Markdown – so you can structure your questions and answers in all the ways Markdown syntax allows.

The [current layout template](https://github.com/themefisher/airspace-hugo/blob/master/layouts/_default/faq.html) simply adds a floating ToC of the Markdown content, nada màs.

A PR bringing a more sophisticated FAQ layout would be very welcome I guess – feel free to submit one!

**Comment by vegetarianinvestor** [comment]
Right. Makes sense. I will work on a FAQ layout and follow up with a PR. Thanks for guiding on the right steps.

**Comment by vegetarianinvestor** [comment]
Just came across a [simple faq theme](https://themes.gohugo.io/theme/hugo-faq-theme/). I will try merge it with hugo. I think the key here would be to merge the html file smartly in order to ignore the title & the banner so that only the menu along with the faqs show up on our faq page.
