### ISSUE TITLE
Creating public html files and hosting at Github Pages

### ISSUE THREAD

**Issue by phil-pappas** [themefisher/airspace-hugo#173]
Hi Salim.

I created public_html folder-files with the ` hugo -D` command and placed the generated files in a github repo.
However, when I try to enable github pages of that repo, the site appears with a 404 error
![image](https://user-images.githubusercontent.com/57324955/119235588-8724e380-bb33-11eb-86fd-c544895544ec.png)

Do you know what I am doing wrong? Have you ever come across with a similar situation?

**Comment by phil-pappas** [comment]
Now it is opening with a broken css
![image](https://user-images.githubusercontent.com/57324955/119236155-2ea31580-bb36-11eb-9a95-a5dc43c22895.png)

**Comment by phil-pappas** [comment]
I fixed it but another problem raised. I had to put ` canonifyURLs = true` but now the images are not loading in the backgrounds

**Comment by phil-pappas** [comment]
For example see the follow: 
![image](https://user-images.githubusercontent.com/57324955/119256115-57232200-bbbf-11eb-8694-8182e3840265.png)

It seems like CSS gets broken (?) Locally it works just fine but its not the case when I push it to github

**Comment by phil-pappas** [comment]
It appears that github autogenerated URL was the problem. `https://phil-pappas.github.io/repo/` cause problems. you need to have a URL without extra slases in the end. e.g. `https://phil-pappas.github.io/`

**Comment by salim-b** [comment]
> It appears that GitHub autogenerated URL was the problem. `https://phil-pappas.github.io/repo/` cause problems. you need to have a URL without extra slashes in the end. e.g. `https://phil-pappas.github.io/`

Yeah, that's what I suspected in https://github.com/themefisher/airspace-hugo/issues/157#issuecomment-838001703 ...
