### ISSUE TITLE
Disabling exisitng pages

### ISSUE THREAD

**Issue by vegetarianinvestor** [themefisher/airspace-hugo#175]
How can I disable an existing page from the website? I tried commenting the menu section as below and that removes the page link from the header as expected but the page can still be accessed through the url like `http://localhost:38605/faq/`. 

Can there be a way to disable the page so that I can enable it later when I plan to re-add it? I want to disable it temporarily for few months. 

```
#menu:
#  main:
#    name: "FAQ"
#    weight: 4
```

Thanks.

**Comment by salim-b** [comment]
Either set `draft = true` in the YAML header of the corresponding content file or don't include it at all in the sources.

And please stop opening issues in this repository for general Hugo questions. Instead I'd recommend to read the [Hugo documentation](https://gohugo.io/documentation/) and, if necessary, ask questions like the above in the [Hugo Discourse forum](https://discourse.gohugo.io/). Thanks.

**Comment by vegetarianinvestor** [comment]
Ok. Thanks.
