### ISSUE TITLE
Adding a fabform.io contact form to the template  

### ISSUE THREAD

**Issue by callagg1** [themefisher/airspace-hugo#184]
Adding a fabform.io contact form to the template

Hello
Since this a static hugo template and has no contact form or database hooked up.
I was wondering if you could add a contact form to the template to use with https://fabform.io the [google forms alternative](https://fabform.io)

It's just a few lines of code

I can update your template or you can if you like and push the changes to your repository

what you think?

Geoff

**Comment by salim-b** [comment]
> Since this a static hugo template **and has no contact form** or database hooked up

This is a bit misleading; the theme already offers support for two form providers: [Netlify Forms](https://docs.netlify.com/forms/setup/) and [Formspree.io](https://formspree.io/). The relevant config section:

https://github.com/themefisher/airspace-hugo/blob/aafd4795d322deeeb3faebdd43eaf4b7543e9a3d/exampleSite/config.toml#L72-L81

> I can update your template or you can if you like and push the changes to your repository

If you'd like to submit a PR adding support for FabForm, please make sure to adapt the config code accordingly (the binary `use_netlify` option won't be suitable in case of > 2 form providers).

**Comment by mehedi-sharif** [comment]
@salim-b Thanks for your prompt answer. Take love from themefisher team . @callagg1 You have your answer . I am going to close this issue
