### ISSUE TITLE
Changing colour of the slider/here-area background

### ISSUE THREAD

**Issue by tonycorreia91** [themefisher/airspace-hugo#189]
Hello,
I don't see any 'scss/home.scss' file. Can you please direct me to where the home.scss file is? It does not appear to be part of the files. 
---
Ok, then go to `scss/home.scss`, at the end you will find `.overlay` class. change your color from here.

also if you like this template, a star to the repository would be fantastic.

_Originally posted by @tfsomrat in https://github.com/themefisher/airspace-hugo/issues/96#issuecomment-696492448_

**Comment by tfsomrat** [comment]
Hello @tonycorreia91 

It doesn't exist now. but you can find overlay in `scss/_common.scss` at line 605. Remember it's the color of the overlay. not the background. thank you

**Comment by tonycorreia91** [comment]
Thank you! I noticed the titling difference now. However, I'm still having a bit of trouble editing. I submitted an additional ticket for the second issue (with SCSS).
