### ISSUE TITLE
Issues with SCSS

### ISSUE THREAD

**Issue by tonycorreia91** [themefisher/airspace-hugo#190]
Hello @tfsomrat ,
I'm using AWS cloud9 to customize the site. I'm having issues when I edit the SCSS files. When I make changes to the SCSS file(s), the changes don't seem to take when I serve the pages locally (i.e., the Hugo doesn't compile the SCSS changes, even after a browser refresh--even though it sees a change in the file). I am using Hugo v0.87.0.

Is there something special that one needs to do with SCSS that you wouldn't have to do with CSS? Is it the version? Could there be something in the definitions code in the index file? 

This appears to be an issue for a few folks with SCSS files.

**Comment by tonycorreia91** [comment]
for example, when I change /themes/airspace/assets/scss/_common.scss
FROM
.overly {
  position: relative;

  &:before {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    right: 0;
    width: 100%;
    height: 100%;
    background: #1d192c;
    opacity: 0.8;
  }
}

TO

.overly {
  position: relative;

  &:before {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    right: 0;
    width: 100%;
    height: 100%;
    background: #fff;
    opacity: 0.1;
  }
}

no changes are rendered.

**Comment by salim-b** [comment]
> Is there something special that one needs to do with SCSS that you wouldn't have to do with CSS? Is it the version?

You need the [**extended** version of Hugo](https://gohugo.io/getting-started/installing/) in order to compile the SCSS files to CSS. Hugo caches the compiled CSS under `resources/` and for convenience, it is [included in this theme's repo](https://github.com/themefisher/airspace-hugo/tree/master/exampleSite/resources/), so users who _don't_ customize the SCSS sources can use the theme with the non-extended version of Hugo.

**Comment by tonycorreia91** [comment]
@salim-b Thank you for responding.
Because I am running Amazon Linux 2, per the `[extended version of Hugo](https://gohugo.io/getting-started/installing/)` above, would I need to simply install the snap package ($ snap install hugo --channel=extended) ? Sorry for the spoon-fed question, I'm just a bit new to this all. I appreciate you taking the time, and appreciate you creating this wonderful theme.

**Comment by tonycorreia91** [comment]
This has been resolved. @salim-b Thank you for the resource. Solution ended up being to start a new environment (perhaps you can overwrite your old one) with the hugo package release (https://github.com/gohugoio/hugo/releases) that included the extended version.
