### ISSUE TITLE
Title SCSS

### ISSUE THREAD

**Issue by tonycorreia91** [themefisher/airspace-hugo#191]
Hello,
I am trying to change the font color for "Title" of the home page (where it says "A Digital Marketing & Design Agency". However, I am unable to locate it in the SCSS code. I thought it'd be under the _common.scss (like lines 251 or 306), but it doesn't appear to relate. Can you please provide the location in the SCSS files that relate to this text?

**Comment by somratpro** [comment]
Hello @tonycorreia91 

You can find this in `scss/templates/_slider.scss` at line 17. thank you

**Comment by tonycorreia91** [comment]
Gracias!
