### ISSUE TITLE
"More" with language set to Italian is displayed twice

### ISSUE THREAD

**Issue by jacob-emery** [themefisher/airspace-hugo#192]
In Italian "More" is displayed twice: as "Più" and "More".
To fix this it is needed to replace `parent: "More"` with `parent: "Più"` inside the files `faq.md`, `pricing.md` and `services.md` (in `exampleSite/content/italian`).

**Comment by salim-b** [comment]
Thanks for reporting this, you're right indeed. #193 will fix this.
