### ISSUE TITLE
Empty spaces in tags issue

### ISSUE THREAD

**Issue by jacob-emery** [themefisher/airspace-hugo#194]
There is a problem when selecting tags that include empty spaces (the issue isn't present if you click on a big tag, only on the small ones in the list of articles or on top of the opened article).

To fix the issue open `layouts/_default/single.html` and `layouts/_default/list.html` and replace `.lower` with `.urlize`. I.e. replace

```
<li><i class="ion-pricetags"></i>
  {{ range $index, $elements:= .Params.tags }}{{ if ne $index 0 }}, {{ end }}<a href="{{ `tags/` | relLangURL }}{{. | lower}}">{{ . }}</a>{{ end }}
</li>
```

with

```
<li><i class="ion-pricetags"></i>
  {{ range $index, $elements:= .Params.tags }}{{ if ne $index 0 }}, {{ end }}<a href="{{ `tags/` | relLangURL }}{{. | urlize}}">{{ . }}</a>{{ end }}
</li>
```

**Comment by salim-b** [comment]
Thanks for reporting this, you're absolutely right, these are bugs. #195 will fix this.
