### ISSUE TITLE
Deploy Failed on netlify

### ISSUE THREAD

**Issue by Mosesdejaviano** [themefisher/airspace-hugo#197]
This is what netlify says;
11:26:23 PM: Build ready to start
11:26:25 PM: build-image version: fa439ad1ab9393b2c0d449d8d7c033927683f4b0
11:26:25 PM: build-image tag: v4.3.0
11:26:25 PM: buildbot version: bfa1ece451875e5fe124c5b0a59bb85e0abb8d50
11:26:26 PM: Fetching cached dependencies
11:26:26 PM: Failed to fetch cache, continuing with build
11:26:26 PM: Starting to prepare the repo for build
11:26:26 PM: No cached dependencies found. Cloning fresh repo
11:26:26 PM: git clone https://github.com/Mosesdejaviano/airhugo
11:26:27 PM: Preparing Git Reference refs/heads/master
11:26:27 PM: Parsing package.json dependencies
11:26:28 PM: Starting build script
11:26:28 PM: Installing dependencies
11:26:28 PM: Python version set to 2.7
11:26:29 PM: Downloading and installing node v16.9.1...
11:26:29 PM: Downloading https://nodejs.org/dist/v16.9.1/node-v16.9.1-linux-x64.tar.xz...
11:26:29 PM: Computing checksum with sha256sum
11:26:29 PM: Checksums matched!
11:26:32 PM: Now using node v16.9.1 (npm v7.21.1)
11:26:32 PM: Started restoring cached build plugins
11:26:32 PM: Finished restoring cached build plugins
11:26:33 PM: Attempting ruby version 2.7.2, read from environment
11:26:34 PM: Using ruby version 2.7.2
11:26:34 PM: Using PHP version 8.0
11:26:34 PM: Installing Hugo 0.87.0
11:26:35 PM: hugo v0.87.0-B0C541E4+extended linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
11:26:35 PM: Started restoring cached go cache
11:26:35 PM: Finished restoring cached go cache
11:26:35 PM: go version go1.16.5 linux/amd64
11:26:35 PM: go version go1.16.5 linux/amd64
11:26:35 PM: Installing missing commands
11:26:35 PM: Verify run directory
11:26:37 PM: ​
11:26:37 PM: ────────────────────────────────────────────────────────────────
11:26:37 PM:   Netlify Build                                                 
11:26:37 PM: ────────────────────────────────────────────────────────────────
11:26:37 PM: ​
11:26:37 PM: ❯ Version
11:26:37 PM:   @netlify/build 18.8.0
11:26:37 PM: ​
11:26:37 PM: ❯ Flags
11:26:37 PM:   baseRelDir: true
11:26:37 PM:   buildId: 613d2d0f51f3c53ce863374d
11:26:37 PM:   deployId: 613d2d0f51f3c53ce863374f
11:26:37 PM: ​
11:26:37 PM: ❯ Current directory
11:26:37 PM:   /opt/build/repo
11:26:37 PM: ​
11:26:37 PM: ❯ Config file
11:26:37 PM:   /opt/build/repo/netlify.toml
11:26:37 PM: ​
11:26:37 PM: ❯ Context
11:26:37 PM:   production
11:26:37 PM: ​
11:26:37 PM: ────────────────────────────────────────────────────────────────
11:26:37 PM:   1. build.command from netlify.toml                            
11:26:37 PM: ────────────────────────────────────────────────────────────────
11:26:37 PM: ​
11:26:37 PM: $ cd exampleSite && hugo --gc --themesDir ../..
11:26:37 PM: Start building sites …
11:26:37 PM: hugo v0.87.0-B0C541E4+extended linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
11:26:37 PM: Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/contact.html:50:152: executing "main" at <partial "cloak_email" .email>: error calling partial: "/opt/build/repo/layouts/partials/cloak_email.html:5:167": execute of template failed: template: partials/cloak_email.html:5:167: executing "partials/cloak_email.html" at <len $domain>: error calling len: reflect: call of reflect.Value.Type on zero Value
11:26:37 PM: Total in 168 ms
11:26:37 PM: ​
11:26:37 PM: ────────────────────────────────────────────────────────────────
11:26:37 PM:   "build.command" failed                                        
11:26:37 PM: ────────────────────────────────────────────────────────────────
11:26:37 PM: ​
11:26:37 PM:   Error message
11:26:37 PM:   Command failed with exit code 255: cd exampleSite && hugo --gc --themesDir ../..
11:26:37 PM: ​
11:26:37 PM:   Error location
11:26:37 PM:   In build.command from netlify.toml:
11:26:37 PM:   cd exampleSite && hugo --gc --themesDir ../..
11:26:37 PM: ​
11:26:37 PM:   Resolved config
11:26:37 PM:   build:
11:26:37 PM:     command: cd exampleSite && hugo --gc --themesDir ../..
11:26:37 PM:     commandOrigin: config
11:26:37 PM:     environment:
11:26:37 PM:       - HUGO_VERSION
11:26:37 PM:       - HUGO_THEME
11:26:37 PM:       - HUGO_BASEURL
11:26:37 PM:     publish: /opt/build/repo/exampleSite/public
11:26:37 PM:     publishOrigin: config
11:26:37 PM:   redirects:
11:26:37 PM:     - from: /de/*
      status: 404
      to: /de/404.html
    - from: /fr/*
      status: 404
      to: /fr/404.html
    - from: /it/*
      status: 404
      to: /it/404.html
    - from: /*
      status: 404
      to: /404.html
  redirectsOrigin: config
Caching artifacts
11:26:37 PM: Started saving build plugins
11:26:37 PM: Finished saving build plugins
11:26:37 PM: Started saving pip cache
11:26:37 PM: Finished saving pip cache
11:26:37 PM: Started saving emacs cask dependencies
11:26:37 PM: Finished saving emacs cask dependencies
11:26:37 PM: Started saving maven dependencies
11:26:37 PM: Finished saving maven dependencies
11:26:37 PM: Started saving boot dependencies
11:26:38 PM: Finished saving boot dependencies
11:26:38 PM: Started saving rust rustup cache
11:26:38 PM: Finished saving rust rustup cache
11:26:38 PM: Started saving go dependencies
11:26:38 PM: Finished saving go dependencies
11:26:40 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:26:40 PM: Creating deploy upload records
11:26:40 PM: Failing build: Failed to build site
11:26:40 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
11:26:40 PM: Finished processing build request in 14.791293429s

**Comment by salim-b** [comment]
This is probably because you either didn't set `params.contact.email` in `config.toml`, or you've set it to an invalid e-mail address. I've improved the template code in #198 to properly handle both cases.

**Comment by Mosesdejaviano** [comment]
Thanks, the Issue has been solved now with the improved template.
