### ISSUE TITLE
poor design

### ISSUE THREAD

**Issue by inVisement** [themefisher/airspace-hugo#20]
This is a beautiful template, implemented not so great. Sorry for complaining, but it worked 4 hours without being able to get one page working. It seems it is designed to work with example site and nothing else.

- How do you change the images in landing page and their sizes?
- How do you add multiple feature section or multiple buttons in feature?
- Why some section (like feature) accept html tags in content but other sections do not?
- How do you remove Home link in top menu? Why there is home by default?! if needed, can be added.
- How do you add project or work or other folders (other than blog)?
- Why is it so complicated? Why not one config file (without data folder?) or read data from md files in folders?

I tried to customize but failed and gave up.
Wish you best.

**Comment by divinerites** [comment]
I guess you have to deal with this theme logic.
Works fine for me while you dig how it works.

If you fork for a better one, let us know.

**Comment by mehedi-sharif** [comment]
@inVisement  I think its not the issue with them theme . First you have to understand the basic idea of hugo templating (as far as I think). Hope this link will help you to get your answers https://gohugo.io/documentation/
Thanks
