### ISSUE TITLE
Issue Deploying on Netlify

### ISSUE THREAD

**Issue by Mosesdejaviano** [themefisher/airspace-hugo#200]
I have tried all my best to deploy this site on netlify but it keeps saying deploying failed, This is the build log;

9:30:38 AM: Build ready to start
9:30:40 AM: build-image version: fa439ad1ab9393b2c0d449d8d7c033927683f4b0
9:30:40 AM: build-image tag: v4.3.0
9:30:40 AM: buildbot version: ddbb47739f5b85c954aad9dc3823ab0676432957
9:30:40 AM: Building without cache
9:30:40 AM: Starting to prepare the repo for build
9:30:40 AM: No cached dependencies found. Cloning fresh repo
9:30:40 AM: git clone https://github.com/Mosesdejaviano/jokelinks
9:30:41 AM: Preparing Git Reference refs/heads/master
9:30:41 AM: Error checking out submodules: fatal: No url found for submodule path 'themes/airspace-hugo' in .gitmodules
9:30:42 AM: Creating deploy upload records
9:30:42 AM: Failing build: Failed to prepare repo
9:30:42 AM: Failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'themes/airspace-hugo' in .gitmodules
: exit status 128
9:30:42 AM: Finished processing build request in 1.942923374s

Thanks i really appreciate

**Comment by salim-b** [comment]
Seems your Git submodule config is broken.

The content of your `.gitmodules` file should look similar to this:

```ini
[submodule "themes/airspace"]
	path = themes/airspace
	url = https://github.com/themefisher/airspace-hugo.git
	branch = master
```

**Comment by Mosesdejaviano** [comment]
I dont even know where the .gitmodules is? Please where is it located?
