### ISSUE TITLE
In the Language Selection menu, Italian language is seen twice

### ISSUE THREAD

**Issue by offense360** [themefisher/airspace-hugo#202]
In the Language Selection menu, Italian language is seen twice and German is not seen.

**Comment by salim-b** [comment]
This is because of a copy-paste mistake in the recent changes made by @sojonatgithub , see https://github.com/themefisher/airspace-hugo/commit/50f67a97956341aff605d4d9e4368925ab82006f#diff-d187a2ea9a18ddc439549d681fe5451bf4f329f3c498db6a6dd7f2b0ede0c790
