### ISSUE TITLE
Banner and background images don't scale correctly on ipad in landscape mode

### ISSUE THREAD

**Issue by githubmonkey** [themefisher/airspace-hugo#206]
Banner and background images don't scale down to fit the page in landscape mode on my tablet. 

In your demo it looks like the images weren't loading at all (monocrome background) but I think that's just because the images have so little contrast that they look like a plain color background when zoomed in extremely. 

Portrait mode works well, the problem only shows in landscape. I tried chrome and safari, both behave the same so it doesn't seem browser dependent. 

Device used: 6th gen IPad, ios 14.7.1

**Comment by fredleger** [comment]
even worst on iphone SE 2 or XR

**Comment by tfsomrat** [comment]
Hello @fredleger @githubmonkey 

Thanks for letting us know about this issue. It is fixed now. you can pull the latest code and enjoy it.

**Comment by AlbSrd** [comment]
Sorry to reply to this closed issue but i get the same error about homepage banner image scaling.
The image scales good if the broweser web page is less then 1200px wide but, if it's more then that size, I get a "zoomed" banner image and it is no longer centered.
Tested with Safari, Chrome and Firefox.
Do you have a suggestion on how can i fix this behaviour? thank you

**Comment by somratpro** [comment]
hello @AlbSrd 

I recommend you to try a large image, otherwise, it will scale up to fill the entire banner.

**Comment by AlbSrd** [comment]
> 

i tested up to an 8k image and the image is "zoomed" when I see it in a web page larger then 1200px. The "zoom" effect is not centered too, it is like zoomed in the upper-center zone of the image
