### ISSUE TITLE
Error in .htaccess

### ISSUE THREAD

**Issue by githubmonkey** [themefisher/airspace-hugo#212]
This line in your exampleSite cased problems with one of my hosting services. (Regex could not be compiled, Apache 2.4.51)
`<FilesMatch *.(html|css|jpg|jpeg|webp|png|gif|js|ico)>`

When I changed it to `<FilesMatch ".(html|css|jpg|jpeg|webp|png|gif|js|ico)">` things started working again.

**Comment by tfsomrat** [comment]
Thanks for fixing me up. I fixed it.
