### ISSUE TITLE
Google Map Not Loading

### ISSUE THREAD

**Issue by tonycorreia91** [themefisher/airspace-hugo#214]
It looks like this issue has already been brought up, but I did not see a solution. I'm not sure how to load the Google Map correctly. I'm in the config file, and I'm guessing the issue has to do with the "gmap_api" field, but I'm not sure how to get it to load correctly. The error message that I'm receiving when I run it locally is "This page can't load Google Maps correctly."

**Comment by tfsomrat** [comment]
Hello @tonycorreia91 

You need to generate your own Map API key to solve this issue. You can follow [this](https://setcompass.com/How-to-Get-Google-Maps-API-Key-Guide.htm) tutorial, or maybe others, and generate your API key. Thanks
