### ISSUE TITLE
Request for better error output

### ISSUE THREAD

**Issue by afs2015** [themefisher/airspace-hugo#24]
I'm new to Hugo and one issue I had using this template is when I was following the [quickstart tutorial for Hugo](https://gohugo.io/getting-started/quick-start/#step-4-add-some-content) I ran into this error.

```
hugo server -D
Building sites … ERROR 2018/07/13 14:33:01 Error while rendering "page" in "posts/": template: _default/single.html:20:126: executing "_default/single.html" at <.Site.Params.datefor...>: invalid value; expe
```

I managed to solve it by adding the following code to my config.toml file:
`[params]
dateformat = "July 13, 2018"`

Would it be possible to edit the error message thrown to ask users to check if they configured dateformat in their config.toml file? I think this could create a better install experience for newer users.

**Comment by mehedi-sharif** [comment]
Hey @afs2015  I think its not a error from our end . You should post this issue to hugo forum . But yes I will recheck this issue . If it is from our end. We will fix this as soon as possible .

**Comment by mehedi-sharif** [comment]
@kausarpial  could you please check this issue .

**Comment by kausarpial** [comment]
You should give the dateformat in config.toml. We can't control the hugo errors messages because it's generated by defaults from HUGO. We will update the theme for not showing the dates if their is no dateformat in config.toml file
Thanks
