### ISSUE TITLE
I wrote a shortcode for using OpenStreetMap instead of GoogleMaps

### ISSUE THREAD

**Issue by divinerites** [themefisher/airspace-hugo#25]
As you are actively maintaining this beautiful theme, just to let you know that if you want to offer a really free alternative for mapping location I wrote a shortcode for that

See https://discourse.gohugo.io/t/shortcode-for-openstreetmap-instead-of-googlemaps/12965

**Comment by mehedi-sharif** [comment]
Thanks for your contribution . If you have a low users I think google map is fine . But open street map has some limitation as far as I know. I will add your issue as alternative . If someone want to use your solution they can :)
