### ISSUE TITLE
Testimonial `enable` switch set to false does not disable subsection

### ISSUE THREAD

**Issue by madonius** [themefisher/airspace-hugo#39]
### Hugo version
```bash
> $ hugo version
Hugo Static Site Generator v0.53/extended linux/amd64 BuildDate: unknown
```
### Observed behaviour
When `enable: false` is set in `data/en/testimonial.yml` the subsection on the website is still rendered.

### Expected behaviour 
When `enable: false` is set in `data/en/testimonial.yml` the subsection on the website is not rendered

_**Note**: This has been observed with a freshly downloaded version of the theme_

**Comment by Somrat37** [comment]
hey @madonius,
thanks for inform us this issue, i fixed this. u can check it out.
