### ISSUE TITLE
A recent commit seems to have broken this theme

### ISSUE THREAD

**Issue by AdrienKG** [themefisher/airspace-hugo#40]
I believe commit 1676ca15a1aced95cbd95f9e5fda47506f3f8691 has broken the theme. The demo page cannot seem to load images anymore. And the "Work" page doesn't load properly, there seems to be an infinite loop of 404s.

I have to revert to commit cf177e69f16a969b93de9c424314d25681f59265 in my project for the page to load as it previously did.

**Comment by mehedi-sharif** [comment]
The issue has been fixed .

**Comment by Janwalli** [comment]
Hi,
since the last two commits, the gallery stopped working for me when publishing the site. It works fine when running hugo server.
This is the output:
```
<script type="text/javascript">
    var css = document.createElement('link');
    css.rel = 'stylesheet';
    css.href = "https:\/\/mysite.com\/css/owl.carousel.css";
    css.type = 'text/css';
    var fastCSS = document.getElementsByTagName('link')[0];
    fastCSS.parentNode.insertBefore(css, fastCSS);
```
It looks like the script url´s are broken.
