### ISSUE TITLE
Disabling Venobox

### ISSUE THREAD

**Issue by mherd12** [themefisher/airspace-hugo#43]
I need help disabling the venobox feature on the portfolio page that enlarges the photos when they are clicked on. That part of theme is not helpful in displaying our portfolio because we want users to be able to click the photo to link elsewhere, enlarging the photo is unnecessary. I haven't been able to find a way to do this without breaking the site.

**Comment by Somrat37** [comment]
hey @mherd12 ,
for disabling venobox and insert a link on portfolio you need to go to this path `themes/layouts/partials/work.html` and find `<a class="venobox" href="{{ $.Site.BaseURL }}{{ .image }}">` this line of code. after that you can just remove the `venobox` class and in `href` just put `{{ .URL}}` and then go to this following path `data/work.yml` and in portfolio section just add another line in the loop, the line should be `URL : "#"`. that is how u can solve your problem without breaking the site.
