### ISSUE TITLE
Empty response sent for docs link

### ISSUE THREAD

**Issue by josh-cain** [themefisher/airspace-hugo#46]
Line 45 of README.md references: http://demo.themefisher.com/airspace-hugo/blog/installation/ .  However, this link returns a blank page when accessed.  Where is the correct link?

`➜  ~ curl -v http://demo.themefisher.com/airspace-hugo/blog/installation/
*   Trying 67.205.170.232...
* TCP_NODELAY set
* Connected to demo.themefisher.com (67.205.170.232) port 80 (#0)
> GET /airspace-hugo/blog/installation/ HTTP/1.1
> Host: demo.themefisher.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 10 May 2019 02:49:44 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: EasyEngine 3.7.5
<
* Connection #0 to host demo.themefisher.com left intact
`

**Comment by Somrat37** [comment]
hey @josh-cain ,
yeah, this link is broken. we don't know why hugo demo server is not showing this page. but i can help you, are you looking for theme installation documentation? [here](https://youtu.be/1wKDqma9Hl0) is the video documentation for install this theme. and if you need more information, then you can check this [page](http://demo.themefisher.com/airspace-hugo/blog/creating-a-new-theme/).

**Comment by josh-cain** [comment]
@Somrat37 Nah, I just wanted to double-check to validate my installation was configured properly - investigating why the blog feature wasn't working.  However, this was answered on #48 .  No further action needed here if y'all are aware the link is down on the demo sever.
