### ISSUE TITLE
Blog Landing Page - Where Is It?

### ISSUE THREAD

**Issue by josh-cain** [themefisher/airspace-hugo#48]
In your [example site](http://demo.themefisher.com/airspace-hugo/
), there's a [blog link](http://demo.themefisher.com/airspace-hugo/blog/).  However, I'm unable to find any of the page partials/elements for a blog in the repo, or any docs on how to configure it with your theme (although I've been able to configure blogs for other themes in the past).

Is this an intentional omission, or am I just missing something obvious here?  Also opened an issue because the link for the instructions is invalid :( , otherwise I'd go RTFM.

**Comment by Somrat37** [comment]
hey @josh-cain , in this repository we provide a free version of our airspace hugo theme. that's why you could not find the blog section. In our [premium version](https://themefisher.com/products/airspace-hugo/)  we provide all features, thanks.

**Comment by josh-cain** [comment]
Sounds good - just a recommendation though: You don't list "blog" under "Premium Features".  What's more, you have pictures in the free version of the blog template page.  Was very misleading, and actually quite frustrating as I spent time pouring over my configs + site structure for a while.

I'm an open source developer too, and I'll probably wind up purchasing the theme (I think good work should be paid for!).  However, experiences like this ^ can leave a bad taste in folks' mouths - clear expectations on what's free/open and what's not is key!

**Comment by mehedi-sharif** [comment]
Hello @josh-cain ,
I am so sorry the issue you are facing . Actually we are new in this era of open source . Being a new company we made mistakes and we always try to learn from our mistakes . And user feedback is very important for us . After seeing your comment I thought we should take a clear step with this theme. By tomorrow we will make a clear statement and also fix this kind of confusion. Thanks for your opinion .
Thanks

**Comment by mehedi-sharif** [comment]
congrats @josh-cain  , Based on your suggestion , we have added blog in free version . Keep inspiring us.  
Thanks

**Comment by josh-cain** [comment]
Wow - that's great news @mehedi-sharif !  Thanks for taking the feedback!

P.S. had gone ahead and bought the pro version.  Nice work on the templates, keep it up ;-)
