### ISSUE TITLE
Error hugo server

### ISSUE THREAD

**Issue by tattooseoul** [themefisher/airspace-hugo#49]
I get 4 different errors when I run the command "hugo server":

ERROR 2019/06/03 19:38:10 Failed to add template "theme/partials/work.html" in path "/home/kong/Hugo/test/themes/airspace-hugo/layouts/partials/work.html": template: theme/partials/work.html:13: unexpected "=" in operand

**Comment by k-jackson** [comment]
You need to update to the latest version of Hugo.

Go to https://github.com/gohugoio/hugo/releases and install the most current version in the format appropriate for your OS.
