### ISSUE TITLE
Full Documentation link is broken & Unable to use this theme

### ISSUE THREAD

**Issue by codenio** [themefisher/airspace-hugo#53]
Hi,

I came across the following issue while trying to use this theme.
- Followed the installation steps
   ```
    $ mkdir themes 
    $ cd themes
    $ git clone https://github.com/themefisher/airspace-hugo.git
   ```
   but it fails to load static files during the build using `hugo` command

- Tried to build using `hugo -t themes/airspace-hugo` command
  ```
  Error: module "themes/airspace-hugo" not found; either add it as a Hugo Module or store it in "/my-website/themes".: module does not exist
  ```
- Full Documentation link in README.md is broken

unable to fix this issue. can you help here..?

**Comment by Somrat37** [comment]
@codenio , you can follow this [video tutorial](https://www.youtube.com/watch?v=1wKDqma9Hl0)

**Comment by codenio** [comment]
@Somrat37, thanks for the response.
managed to overcome this issue recently.

**Comment by mehedi-sharif** [comment]
@codenio  Great to hear that you fixed your issue by yourself . And thanks for creating your website with our theme

**Comment by codenio** [comment]
FYI, The full documentation is still broken. I hope you can get it fixed soon.
