### ISSUE TITLE
Sub menu possible?

### ISSUE THREAD

**Issue by snieders** [themefisher/airspace-hugo#54]
Hi,

thank you for the beautiful Hugo theme, I really love it. The template was the number one reason to start with Hugo (still learning). I have one question. Is it possible to create a sub menu? 

Something like this:

  [[menu.header]]
      weight = 2
      name = "About"
      url = "#about"
    [[menu.header]]
      weight = 3
      name = "Work"
      url = "work"
    [[menu.header]]
      weight = 3
      name = "Work"
      url = "work"
    [[menu.header]]
      **weight = 3.1**
      name = "Work a"
      url = "work_a"
    [[menu.header]]
      **weight = 3.2**
      name = "Work B"
      url = "work_b"
    [[menu.header]]
      weight = 4
      name = "Blog"
      url = "blog"

Thank you for your reply.

**Comment by Somrat37** [comment]
Hey @snieders , yes! sub menu is possible, for creating a submenu you need to know some coding knowledge, you can follow this [Documentation](https://gohugo.io/templates/menu-templates/) for creating a sub menu. Or you can buy [Airspace Hugo Premium](https://themefisher.com/products/airspace-hugo/) theme. Thanks

**Comment by snieders** [comment]
Thank you, willl have a look at the premium version!
