### ISSUE TITLE
@import vs <link> for fonts?

### ISSUE THREAD

**Issue by dakkusingh** [themefisher/airspace-hugo#57]
Hi guys,
Any thoughts on changing out the font @import for a `<link>` instead?
Reason being that I am trying to concat and minify and imports arnt working anymore for obvious reasons.

Thoughts?

**Comment by Somrat37** [comment]
Hi there,
We used @import in css for font-family. and declare it in h1-h6 and every other tag. so if you want to change the font family, you need to customize the css file.

**Comment by dakkusingh** [comment]
My question was more around - can we change the import for a link instead? This is due to the issue I explained above.

**Comment by Somrat37** [comment]
Yes, you can do it, but first you should remove the @import from css and replace the font-family with whatever font you want to use.
