### ISSUE TITLE
themes works local host but on Netlify

### ISSUE THREAD

**Issue by lucifer911** [themefisher/airspace-hugo#60]
Hello,
I was able to use "git submodule add <theme link>" to upload theme to github. But when I go to see the live website, It does not load CSS. Just a simple static page.

**Comment by lucifer911** [comment]
Trying to use it on Hugo 0.60.1

**Comment by divinerites** [comment]
without depot access it is impossible to help.

But generally this is a problem with a wrong baseURL on config.toml.

**Comment by lucifer911** [comment]
Yes you were right . Base URL was wrong. It works now.

**Comment by lucifer911** [comment]
One more thing. How can i disable the language?
Thank you.

**Comment by divinerites** [comment]
https://gohugo.io/content-management/multilingual/#disable-a-language

**Comment by lucifer911** [comment]
thx
