### ISSUE TITLE
Can not locate Portfolio button labels to edit their names

### ISSUE THREAD

**Issue by maxmooremedia** [themefisher/airspace-hugo#62]
Can someone please direct me to the file/s where I can edit the label text for the buttons "All" UI/UX Design, Video, Illustrations in the Airspace | Creative Agency theme.  I have searched everywhere ie YAML files, CSS, SCSS but can only locate these labels in 'Public' (after the fact) once the GOHUGO html generator has weaved its magic.

I am really looking forward to having my problem resolved.

Thanks,
Max

**Comment by themefisherDev** [comment]
Hey, The filter buttons generate from the portfolio category. when you define the portfolio category, it will automatically make a filter button.

**Comment by maxmooremedia** [comment]
Thanks heaps... So simply and I am so stupid.
