### ISSUE TITLE
issue #21 still present. Bootstrap 4 solves the bug.

### ISSUE THREAD

**Issue by divinerites** [themefisher/airspace-hugo#63]
1. 1. Following #21, I have now the same exact problem but I can't adjust all my texts. Even with latest Bootstrap3 (3.4.1). You can see the problem live at https://www.cocoon-arolla.com.
2. I made an attempt to update to Bootstrap 4 (4.4.1) and the bug is gone. Bootstrap 4 behave well whatever the text is.
3. But updating bootstrap creates problems with the menu who disapears.

Question is : Any plan to upgrade to bootstrap 4 ? Or any tip about needed changes to the menu if you have experience migrating for B3 to B4 ??

**Comment by themefisherDev** [comment]
Hey, thanks for your concern. If you upgrade it B3 to B4 without the navigation and make a pull request, then i'll fix the navigation. is it ok to you?

**Comment by divinerites** [comment]
Oh, didn't notice your response sorry !.

I just realize that I use version 1 of this theme. So will not be able to test on my site and make a PR for the version 2 ... May be if I upgrade to v2 ...

Anyway thanks for your (always) great & hard work.

**Comment by developer-evan** [comment]
I am going to close this issue, if you feel something is not right, then reopen or create a new one. thanks
