### ISSUE TITLE
The preloader make Firefox and IE stop showing in most cases

### ISSUE THREAD

**Issue by majj** [themefisher/airspace-hugo#64]
The preloader make Firefox(74) and IE(11) stop showing in most cases, but on Chrome it is OK.

**Comment by Somrat37** [comment]
This could be happened for your internet speed.

**Comment by majj** [comment]
I tested it on localhost. But Chrome is OK

**Comment by Somrat37** [comment]
I checked on IE, but it's ok. And no one has this issue.
