### ISSUE TITLE
preloader doesn't fadeout on firefox

### ISSUE THREAD

**Issue by AaronCleaver** [themefisher/airspace-hugo#76]
When opening the example site with firefox 74.0 the preloader div doesn't get faded so the screen remains plain white.  (if you hit crtl-R repeatedly it correctly display approx 1 time out of 20).

Seems to be a race condition between the document.ready and window.load events. 

fix should be to move the registering of the function for the load event outside of the ready function like this theme
https://themes.gohugo.io/theme/infinity-hugo/js/main.js

 ❯ go version
go version go1.13.3 linux/amd64
 ❯ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: unknown

**Comment by Somrat37** [comment]
Thanks for your concern, i fix this issue, please take a pull.
