### ISSUE TITLE
allow for shortcodes in content files?

### ISSUE THREAD

**Issue by dklinges9** [themefisher/airspace-hugo#77]
Hi team,

I'm only modestly experienced with YAML and hugo sites, so apologies if this issue is unclear/not endemic to the theme/I'm missing something fundamental about using shortcodes.

I tried adding a shortcode (layouts/shortcodes/myshortcode.html) to one of the markdown files (content/english/faq/_index.md), and it appears that the content of the shortcode itself is passed into the content file, rather than rendering the shortcode.

I'm pulling from a [hugo tutorial for a simple one-tag shortcode](https://gohugo.io/templates/shortcode-templates/).

shortcode.html content:
```
<p style =“color:{{.Get `color`}}”>this is the framework text</p>
```
faq/_index.md content:
```
---
title: "Frequently Asked Questions"
description: "this is meta description"
subtitle : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi, repudiandae."
date: 2019-12-23T13:05:29+06:00
draft: false
bg_image: "images/featue-bg.jpg"
---

### Welcome to Airspace!

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia ullam sint quas pariatur ipsam nemo
repellendus suscipit quod accusantium numquam tempora assumenda sequi, velit voluptatem soluta voluptatibus
nesciunt ducimus iure. Excepturi voluptatum ullam tenetur perspiciatis alias delectus beatae voluptatibus
magni facere aspernatur, qui, quas nesciunt blanditiis assumenda a expedita accusantium quos consectetur neque
nemo.

{{< myshortcode color="blue">}}

```

which renders as such:

<img width="790" alt="Screen Shot 2020-04-05 at 9 32 35 AM" src="https://user-images.githubusercontent.com/36737801/78499682-287a8b80-7720-11ea-91a6-e1ff65f03371.png">

Ultimately I hope to be embedding youtube videos or other pages into the content files, which I've been able to do using other Hugo themes but not here....

Thanks!

**Comment by Somrat37** [comment]
hey there, you had a simple mistake.
please replace your shortcode with this `<p style="color:{{.Get `color`}}">this is the framework text</p>`

**Comment by Somrat37** [comment]
Did it solve your issue? I am going to close this issue, if you face any more issues, don't hesitate to reopen it.

**Comment by dklinges9** [comment]
Apologies for the late reply (my website dev work is sporadic)– this didn't seem to change anything– I pasted your suggestion into the short code, and did some further messing around. What exactly was different between my short code and your edit?

my version:
```
<p style =“color:{{.Get `color`}}”>this is the framework text</p>
```
your version:
```
<p style="color:{{.Get color}}">this is the framework text</p>
```

you took away the space after "style" and didn't have "color" in single quotes (but I think that part was the markdown rendering of the comment)?

**Comment by somrat-gyver** [comment]
no, just look at the quotation, you entered the wrong quotation. it should "" , not “”
