### ISSUE TITLE
What is the technique to upgrade from Bootstrap 3.x to 4.x?

### ISSUE THREAD

**Issue by javajon** [themefisher/airspace-hugo#81]
I tried replacing bootstrap plugin with 4.x and it broke the menu and a few other layouts. I suspect I did not follow the correct course to upgrade. What is the correct way to update to B4 in AirSpace?

The motivation is I'm looking for bootstrap cards in B4 for an events page as found in: https://themes.gohugo.io/theme/educenter-hugo/event

Would it be possible for this theme to upgrade to B4?

**Comment by Somrat37** [comment]
Yes, it is possible, but you need to have full knowledge of bootstrap. Otherwise, you can't do it. Or you can contact us for our paid support at themefisher@gmail.com. 

Thanks
themefisher team.
www.themefisher.com

**Comment by javajon** [comment]
@Somrat37 Thank you. I shifted to educenter theme instead.
