### ISSUE TITLE
dark purple overlay on background image on home page

### ISSUE THREAD

**Issue by SolZiv** [themefisher/airspace-hugo#85]
Hi!

Thanks for the template and for making it available.

I would like to remove the dark purple overlay on the background image in the home page banner (by default: slider-bg.jpg). I played around with layouts\index.html and with assets\scss\templates\_slider.scss but I could not figure it out.

Could you let me know what would I need to adjust to change this and have the original picture there without any overlay?

**Comment by somrat-gyver** [comment]
Hey there, i have added this facility to remove the overlay. please download the latest code and you can see `bg_overlay` in data/homepage.yml file. you can make it false to disable overlay. thanks

**Comment by SolZiv** [comment]
Thank you!
