### ISSUE TITLE
Sending message through "Contact" form

### ISSUE THREAD

**Issue by romain-berthe** [themefisher/airspace-hugo#88]
Hi,

Do you have some documentation about the form on the contact webpage ?
I deploy your theme on my own domain and I'd like to understand how the contact function is working ? Is SMTP used or is it another protocol ?

Thanks a lot !
Romain.

**Comment by developer-evan** [comment]
hey there, you can use https://formspree.io form in this theme. for this, you need to create an account of formspree, then copy the form action and place it on config.toml file (contact_form_action field). action will look like "formspree.io/your.name@email.com"

also if you like our theme, then give a star. it will be amazing. thanks.
