### ISSUE TITLE
I need 2 languages in the website.  How can i set the 2nd language navigation bar?  Seems like only the content can have the 2nd language, not the navigation bar, please advise.  Thanks for your help.

### ISSUE THREAD

**Issue by jen-git** [themefisher/airspace-hugo#89]

**Comment by jen-git** [comment]
i found the answer.  Thank you

**Comment by AgiliaErnis** [comment]
> i found the answer. Thank you

I've the same problem, how did you fix it? when clicking home in any other language it show 404.

**Comment by AgiliaErnis** [comment]
nvm, figured it out too

**Comment by developer-evan** [comment]
hey there, please follow this doc https://gohugo.io/content-management/multilingual/#menus
