### ISSUE TITLE
how to add pictures in YAML of template about page?

### ISSUE THREAD

**Issue by kaeruchan** [themefisher/airspace-hugo#91]
Dear developer 

I want to build a website based on the template of airspace.
I am a beginner in using YAML. So there are some issues of the template confusing me.

I want to ask about the usage of the mission part of about page. I want to add figures in the blank of the mission part. But it seems the articles are written in YAML, and I am not clear how to add pictures in YAML. Can you help me to solve this problem?

Await for your kindly reply.

**Comment by developer-evan** [comment]
Hey there, you want to add an image on `mission` tab right?  Don't worry about YML file. Just remember that every content support's markdown. so you can add an image like your image on markdown file. ex: `![image](../image/your-image.jpg)`

**Comment by kaeruchan** [comment]
Can I change the font size and paragraph style of articles?
