### ISSUE TITLE
How can I add tables in YAML file? 

### ISSUE THREAD

**Issue by kaeruchan** [themefisher/airspace-hugo#92]
Dear developers

I wanna to add the table in the mission_vision of about pages.
I have tried the markdown codes like below

```markdown
|![pic1](..pic1_address)|![pic2](..pic2_address)|
|---|---|
|pic1|pic2|
```

However, the result couldn't correctly displayed.
What should I do?

**Comment by developer-evan** [comment]
I think your issue has been solved in private messages.

**Comment by kaeruchan** [comment]
> I think your issue has been solved in private messages.

Sorry for the response.
Could you tell me where I can check my private messages, please?

**Comment by developer-evan** [comment]
it should support markdown, because we used `markdownify` here. If it doesn't work, then you can use html structure for table. here is an example table:
`
     <table>
        <thead>
          <tr>
            <th>a</th>
            <th>b</th>
            <th>c</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>i</td>
            <td>j</td>
            <td>k</td>
          </tr>
          <tr>
            <td>x</td>
            <td>y</td>
            <td>z</td>
          </tr>
        </tbody>
      </table>
`

**Comment by kaeruchan** [comment]
Thank you!
