### ISSUE TITLE
Gallery on Homepage

### ISSUE THREAD

**Issue by mkz71** [themefisher/airspace-hugo#94]
What is the easy way to implement gallery on homepage?
I am thinking about adding this project page as a section in homepage.

http://demo.themefisher.com/airspace-hugo/project/

Is it possible to do that?

**Comment by developer-evan** [comment]
Hey there, It's possible. If you want to do that, you have to knowledge about Hugo and HTML. Or you can contact us at themefisher@gmail.com for any kind of theme customization (paid).
