### ISSUE TITLE
Cannot locate button color and text color

### ISSUE THREAD

**Issue by yashika51** [themefisher/airspace-hugo#95]
Hi, Thanks for the template. I am not able to locate the text and button color declaration. Also is there a way to change the overlay color. I want to change the color of both the text and button.

**Comment by developer-evan** [comment]
please follow this doc https://docs.gethugothemes.com/guide/#colors-and-fonts

**Comment by yashika51** [comment]
Thanks. Actually I have completed editing the site and it works fine locally but when I try to publish that with github pages the site is unformatted. Only the text gets outputted and theme does not show up. I have changed the baseURL properly in config. Is there anything else that needs to be changed?(I have followed the proper instructions from hugo docs already)

**Comment by developer-evan** [comment]
It only causes is baseURL, you should check it again, or give me the url so i can visit and find this issue, thanks

**Comment by yashika51** [comment]
Hi @developer-evan , I figured that out. It works fine now. Thanks.
