### ISSUE TITLE
Change the colour of the slider/hero-area background

### ISSUE THREAD

**Issue by bigo229** [themefisher/airspace-hugo#96]
Hi, how do i change the colour of the slider/hero-area background is it in _slider.scss i want to change it from black to blue

Many Thanks

**Comment by developer-evan** [comment]
Hey there, I didn't get it properly, because we use background-image in slider and you are talking about the background color. If you want to use solid color, then you first need to remove the bg-image, and then you can set a solid color from `_slider.scss` file.

**Comment by bigo229** [comment]
Hi i still want to use the bg-image & change slider background color from black to blue overlay

**Comment by developer-evan** [comment]
Ok, then go to `scss/home.scss`, at the end you will find `.overlay` class. change your color from here.

also if you like this template, a star to the repository would be fantastic.
