### ISSUE TITLE
Background Image is Too Dark

### ISSUE THREAD

**Issue by mkz71** [themefisher/airspace-hugo#98]
How can I make this background image to be brighter and clearer?
It is too dark and can't see detail in the picture.

<img width="803" alt="Screenshot 2020-09-11 085654" src="https://user-images.githubusercontent.com/6776374/92928504-2b835180-f40d-11ea-88c0-a850f6ae4545.png">

**Comment by developer-evan** [comment]
hey there, you can set `bg_overlay : false` in the `data/en/homepage/line 5`, and you will get rid of this overlay.

also if you like our template, consider giving a star on the repository.
