### ISSUE TITLE
How to configure Google map style?

### ISSUE THREAD

**Issue by mkz71** [themefisher/airspace-hugo#99]
How to configure Google map style?
For example, I need to add color for water or add detail about the marker.

**Comment by developer-evan** [comment]
hey there, you can choose map style from here https://snazzymaps.com/, and paste the style to `static/plugins/google-map/gmap.js` file.

**Comment by mkz71** [comment]
I did that but there is nothing change to my site for the map style.

**Comment by mkz71** [comment]
Nevermind, original template is working fine.
I might update the template somewhere in my project so the map style is not working anymore.

**Comment by mkz71** [comment]
BTW, How can I add text to the marker?

**Comment by developer-evan** [comment]
hey @mkz71 
Actually it's a bit harder to set the text to the marker. You need to edit the main code structure and have knowledge about HTML and HUGO.

We are available for hiring, you can contact us at mehedi@themefisher.com for any kind of customization (paid).
